---
title: "Lab 5"
author: "Sahil Sanghvi"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Question 1

Load the data wk5.csv into R and save it as d5.

```{r}

#(a)
require(tidyverse)
library(tidyverse)

#(b) Input data file
d5 = read.csv("data_wk5.csv")
#(c) Determine the minimum and maximum values of d5. You do not need to save these but 
#    you must show that you printed them out.
quantile(d5$x)
# to find the minimum value
quantile(d5$x)[1]
# to find the maximum value
quantile(d5$x)[5]

#(d) Create a ggplot2 histogram of the \textit{d5} variable. Give the histogram border and fill colours of your liking. Name the $x$-axis ``Values'', and make the title ``Histogram of Values.``
library(ggplot2)
ggplot(d5,aes(x = x, y = after_stat(density))) +
  geom_histogram(binwidth = 1, color = "black", fill = "skyblue")  +
  geom_density(aes(x = x, y = after_stat(density)), col = "green") +
  ggtitle("Histogram of X") + labs(x = "Values")

#    Set the minimum and maximum values on the x-axis so that all data points are represented. For example, if the minimum and maximum values of the variables are 40.4 and 55.6 respectively, you should set the histogram values to be 40 and 56 respectively. Set the binwidth to 2.
library(ggplot2)
ggplot(d5,aes(x = x, y = after_stat(density))) +
  geom_histogram(binwidth = 2, color = "black", fill = "skyblue") + xlim(40,62) +
  geom_density(aes(x = x, y = after_stat(density)), col = "green") +
  ggtitle("Histogram of X") + labs(x = "Values")



```

## Question 2

This question involves gauging whether or not a distribution seems normally distributed.

```{r}

#(a) Does the histogram created in Question 1 seem normally distributed?
# It looks normal ( bell shaped)

#(b) Find the empirical 2.5% and 97.5% quantiles and save them as qlow and qhigh, respectively.
qhigh = quantile(d5$x, probs = 0.975)
qhigh
qlow = quantile(d5$x, probs = 0.025)
qlow
print(paste("Empirical 2.5th and 97.5th Quantiles: (",qlow, ",",qhigh,")"))

#(c) Finding the normal theoretical 2.5% and 97.5% quantiles of x.
x_bar = mean(d5$x)
s_x = sd(d5$x)

sq = qnorm(c(0.025,0.975), mean = x_bar, sd = s_x)
sq
#(d) Are your answers in (b) and (c) close?
# yes

```

